travis:
  secure:
    BINSTAR_TOKEN: C3X8Ha5i+9tXzwbvVdXUIdhHAi5aM4hchgNtw2IbaMdaF7kM+GLmyfVj0aPh1qwblGKjh1aQRglPHmVDUFPkdvHGjuwChOI9JFO7rBKrVF3SkC+KoP7M+545mJyOvGP+fFN82D6ldBNm5kDCXfcCfW4MmZzQJNH5lgBwLNLNzrxdAE8/jHg9kfQ7Aj2Zt4vKkMOfo5D7MXdEYs1nop/yMZv2SXzMD1Man1PSaHcCTJHAEZCrDfgchmoja4R4b2/HTZzgGL6U3g2ihQgAnIkew7SGNSt0ZXNTMyaX744IgrpJkrnIuDIChX3Gmfq1wOGvszrn/UrsNOcgqvccntsuEKLDs7oIm8Te9tVw1hPVK4sNnIZC9VCpRtl8HdittiUGRNBnRcCEKKloecDEtNpgyVY1N+MJBtskz2aFG9qQ13JUn98pYcbMHxPKPQnCRQfqIcUiAKF+VfhHB0FP+9KDHiNwYna/pSKBgiKzparUNGHNNJE1icwaMeTyx3PRyJusquFuHH1xtpsmID7jw+F2/rJZkoT2h+qAvzoOlu2SIjHe/7QlWw2mW5+HUNC4LzFDLjXGFCvot8keVhtoSfxmApDV6I/ZgF1uWzFj2/YroOEtNg7cI3TtEdQ9n/DOCaSa1ECe4K4Jt+NG7/ZLn4p0Thm7MKANA9hkXXeFuPMEX2s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
